name: Sync Google Sheet to YAML

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"  # Every day at 9 AM New York time

permissions:
  contents: write
  id-token: write

jobs:
  sync-events:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: scripts

      - name: Run sync script
        env:
          GOOGLE_SHEET_CREDENTIALS: ${{ secrets.GSHEET_CRED }}
        run: python sync_events.py
        working-directory: scripts

      - name: Commit & push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/events.yml _data/events.yml.bak
          git diff --cached --quiet || git commit -m "Auto-sync events from Google Sheets"
          git push